name = 'testcm2-7112'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改

id = "a507339c89454020a424f8b5292141d7"				#KV数据库id

